version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    restart: always
    hostname: postgres
    ports:
      - "5431:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails tailwindcss:build && rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
